### PR TITLE
[enhancement] add some Emacs-like key bindings in prompt

### PR DESCRIPTION
**Pull request by acro5piano**
Thank you for the great tool!

I use Emacs-like key bindings every day in my terminal, such as C-h, C-b, C-n, etc.
So I added them to this tool by changing `autoload/SpaceVim/api/prompt.vim`. 

I'm afraid that I changed wrong file because the file seems to be a part of SpaceVim...
But I'm really glad if you merge my PR.

Best,
Kazuya

### CODE REVIEW

**Comment by wsdjeg** [comment]
Thanks, but what does Ctrl+d means? why it check cursor != end ?

**Comment by acro5piano** [comment]
Thanks for your response!

Ctrl+d means delete current character.
If not check cursor != end, Ctrl+d deletes the character on the left side of the cursor when the cursor is at the end of the prompt.

Like, 

```
abcde■  <-- must not delete "e" !
```

`■` is cursor. 

Thanks!

**Comment by wsdjeg** [comment]
Thanks. merged

**Comment by acro5piano** [comment]
Thank you very much.

**Pull request merged**
